apiVersion: batch/v1
kind: Job
metadata:
  name: specify6-init
  labels:
    app: specify
    component: specify6
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: specify
        component: specify6
    spec:
      restartPolicy: OnFailure
      containers:
      - name: specify6
        image: specifyconsortium/specify6-service:6.8.03
        env:
        - name: TZ
          value: "Australia/Perth"
        volumeMounts:
        - name: specify-storage
          mountPath: /volumes/Specify
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: specify-storage
        persistentVolumeClaim:
          claimName: specify-storage
