apiVersion: apps/v1
kind: Deployment
metadata:
  name: spms-deployment
  labels:
    app: spms-prod
spec:
  selector:
    matchLabels:
      app: spms-prod
  template:
    metadata:
      labels:
        app: spms-prod
    spec:
      initContainers:
        - name: chown-files
          image: busybox
          command:
            - /bin/chown
            - -R
            - '10001:10001'
            - /usr/src/app/backend/files
          volumeMounts:
            - mountPath: /usr/src/app/backend/files
              name: spms-media-prod
      containers:
        - name: spms-backend
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: DATABASE_URL
            - name: DEFAULT_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: DEFAULT_FROM_EMAIL
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: ENVIRONMENT
            - name: EXTERNAL_PASS
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: EXTERNAL_PASS
            - name: IT_ASSETS_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: IT_ASSETS_ACCESS_TOKEN
            - name: IT_ASSETS_USER
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: IT_ASSETS_USER
            - name: LIBRARY_API_URL
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: LIBRARY_API_URL
            - name: LIBRARY_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: LIBRARY_BEARER_TOKEN
            - name: PRINCE_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: PRINCE_SERVER_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: SECRET_KEY
            - name: SENTRY_URL
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: SENTRY_URL
            - name: SPMS_MAINTAINER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: spms-env-prod
                  key: SPMS_MAINTAINER_EMAIL
          volumeMounts:
            - mountPath: /usr/src/app/backend/files
              name: spms-media-prod
        - name: spms-frontend
          imagePullPolicy: IfNotPresent
      volumes:
        - name: spms-media-prod
          persistentVolumeClaim:
            claimName: spms-media-data-prod
