apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: specify-ingress
spec:
  rules:
  - host: specify-dev.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: specify
            port:
              number: 8000
  tls:
  - hosts:
    - specify-dev.yourdomain.com
    secretName: specify-dev-tls
